from PIL import Image
from PIL.ExifTags import TAGS


def compute_metadata_score(image_path):

    image = Image.open(image_path)
    exif_data = image._getexif()

    if not exif_data:
        return {
            "tool_name": "metadata_analysis",
            "status": "success",
            "score": 0.40,
            "details": {
                "risk": 40,
                "camera_confidence": False,
                "suspicious_edit": False,
                "error": "No EXIF data found"
            }
        }

    metadata = {}
    for tag_id, value in exif_data.items():
        tag = TAGS.get(tag_id, tag_id)
        metadata[tag] = value

    make = str(metadata.get("Make", "")).lower()
    model = str(metadata.get("Model", "")).lower()
    software = str(metadata.get("Software", "")).lower()
    image_desc = str(metadata.get("ImageDescription", "")).lower()

    # 🔵 Strong camera metadata
    # 🔵 Strong camera metadata
    if make and model :
        return {
            "tool_name": "metadata_analysis",
            "status": "success",
            "score": 0.05,
            "details": {
                "risk": 5,   # Very low risk
                "camera_confidence": True,
                "suspicious_edit": False,
                "make": make,
                "model": model,
                "software": software
            }
        }

    
    if "photoshop" in software or "gimp" in software:
        return {
            "tool_name": "metadata_analysis",
            "status": "success",
            "score": 0.75,
            "details": {
                "risk": 75,
                "camera_confidence": False,
                "suspicious_edit": True,
                "software": software
            }
        }

    # 🔴 AI keyword detected
    if "artificial intelligence" in image_desc or "generated by ai" in image_desc:
        return {
            "tool_name": "metadata_analysis",
            "status": "success",
            "score": 0.85,
            "details": {
                "risk": 85,
                "camera_confidence": False,
                "suspicious_edit": True,
                "description": image_desc
            }
        }

    return {
        "tool_name": "metadata_analysis",
        "status": "success",
        "score": 0.20,
        "details": {
            "risk": 20,
            "camera_confidence": False,
            "suspicious_edit": False
        }
    }


if __name__ == "__main__":
    meta_data_score = compute_metadata_score("../assests/guntur.jpg")
    print(meta_data_score)
